// src/config/commandScenes.ts
// Complete 58-Command Scene Specifications matching Sections 11 & 12 of Gemini Image Generation System.

export interface CommandSceneSpec {
  command: string;
  category: 'movement' | 'fun' | 'daily' | 'learning' | 'social';
  filename: string;
  environment: string;
  scenePrompt: string;
  cameraPrompt: string;
  lightingPrompt: string;
  svgOverlay?: {
    type: 'stopSign' | 'arrowForward' | 'arrowBackward' | 'arrowLeft' | 'arrowRight' | 'checkmark' | 'cross' | 'countBlocks' | 'target';
    color: string;
    position: 'top-left' | 'top-right' | 'bottom-center' | 'center-right';
  };
}

export const COMMAND_SCENES: Record<string, CommandSceneSpec> = {
  // ==========================================
  // 1. MOVEMENT (13 Commands)
  // ==========================================
  sit: {
    command: 'sit',
    category: 'movement',
    filename: '_sit.png',
    environment: 'Warm cheerful indoor playroom with colorful soft interlocking foam mats and light wooden shelving',
    scenePrompt: 'The character is sitting comfortably and cross-legged on a plush colorful woven circular rug. Natural, relaxed seated posture with hands gently resting on lap, looking forward with a cheerful relaxed smile. The scene unmistakably communicates the action of sitting.',
    cameraPrompt: 'Eye-level child camera, full character visible, 60% of image height, ample headroom and floor clearance',
    lightingPrompt: 'Soft warm global illumination, gentle realistic floor contact shadow',
  },
  stand: {
    command: 'stand',
    category: 'movement',
    filename: '_stand.png',
    environment: 'Bright airy modern children room with soft pastel walls and polished warm timber floor',
    scenePrompt: 'The character is standing upright with well-balanced posture. Full body visible from head to shoes. Confident, friendly expression, arms resting comfortably by sides, feet naturally positioned shoulder-width apart.',
    cameraPrompt: 'Straight-on eye-level 50mm portrait shot, character occupies 65% of frame height, centered, ground clearly visible',
    lightingPrompt: 'Crisp key light with soft ambient fill, subtle cinematic rim light outlining hair and shoulders',
  },
  run: {
    command: 'run',
    category: 'movement',
    filename: '_run.png',
    environment: 'Sunny outdoor park running track with lush green grass, flowering bushes, and soft blurred trees in background',
    scenePrompt: 'The character is actively running with correct athletic biomechanics. One foot pushing off the ground, the opposite knee lifting forward in stride, arms bent rhythmically at ninety degrees, joyful focused expression. Subtle stylized motion cues and gentle cartoon dust particles at feet. The character body itself remains pin-sharp, no blur on face or hands.',
    cameraPrompt: 'Three-quarter action camera, 40mm focal length, character full body clearly framed',
    lightingPrompt: 'Vibrant golden hour sunlight, dynamic natural cast shadow extending along the track',
  },
  jump: {
    command: 'jump',
    category: 'movement',
    filename: '_jump.png',
    environment: 'Safe cheerful indoor activity gym or soft playroom with colorful padded flooring',
    scenePrompt: 'The character is visibly airborne in mid-air during a joyful upward jump. Both feet clearly above the ground with knees tucked slightly, arms raised naturally celebrating. Thrilled laughing expression. Subtle floating 3D golden stars and sparkles emphasizing upward elevation.',
    cameraPrompt: 'Slightly lowered upward-angled child camera capturing clear space between feet and floor, 35mm lens',
    lightingPrompt: 'Bright celebratory studio illumination, dynamic floor shadow beneath character showing height',
  },
  stop: {
    command: 'stop',
    category: 'movement',
    filename: '_stop.png',
    environment: 'Paved clean park walkway with painted crosswalk guidelines and sunny greenery',
    scenePrompt: 'The character is firmly stopped in place. One arm extended forward with an open palm directly facing the viewer in a clear, universal STOP gesture. Serious but child-friendly and approachable facial expression, feet planted firmly together on the pavement.',
    cameraPrompt: 'Eye-level 50mm lens, character dominant in center 65% height, clear palm silhouette',
    lightingPrompt: 'Balanced daytime illumination, distinct grounding shadow',
    svgOverlay: { type: 'stopSign', color: '#EF4444', position: 'top-right' },
  },
  walk: {
    command: 'walk',
    category: 'movement',
    filename: '_walk.png',
    environment: 'Relaxed everyday neighborhood garden path with smooth stone pavers and gentle flowers',
    scenePrompt: 'The character is naturally walking along the path in three-quarter profile. One foot stepped forward, opposite arm swinging gently forward in mid-stride. Relaxed pleasant walking rhythm, subtle colorful stepping footprints trailing behind.',
    cameraPrompt: 'Side-angle 45mm lens capturing lateral walking stride and foot separation clearly',
    lightingPrompt: 'Warm morning daylight, soft diffused shadows under each foot',
  },
  walkForward: {
    command: 'walkForward',
    category: 'movement',
    filename: '_walkForward.png',
    environment: 'Sunny park trail leading straight forward toward the viewer with bright green lawn borders',
    scenePrompt: 'The character is clearly moving forward directly toward the camera. Stepping energetically forward with welcoming open posture, one sneaker planted forward, friendly engaged smile. Perspective and trail demonstrate forward progress.',
    cameraPrompt: 'Frontal eye-level 45mm perspective shot, character walking toward viewer',
    lightingPrompt: 'Directional front-three-quarter sunlight, warm ambient bounce',
    svgOverlay: { type: 'arrowForward', color: '#10B981', position: 'bottom-center' },
  },
  walkBackward: {
    command: 'walkBackward',
    category: 'movement',
    filename: '_walkBackward.png',
    environment: 'Safe spacious outdoor patio with patterned stone tiles',
    scenePrompt: 'The character is carefully and playfully walking backward. Body oriented in reverse stepping motion, glancing slightly over shoulder with a fun playful grin, feet positioned in backward walking cadence.',
    cameraPrompt: 'Three-quarter reverse perspective 45mm lens, clear feet positions',
    lightingPrompt: 'Soft ambient daylight, clean realistic ground shadows',
    svgOverlay: { type: 'arrowBackward', color: '#F97316', position: 'bottom-center' },
  },
  moveLeft: {
    command: 'moveLeft',
    category: 'movement',
    filename: '_moveLeft.png',
    environment: 'Colorful child dance studio with clean polished wood floors and soft mirrors in background',
    scenePrompt: 'The character is stepping sideways toward the left in a graceful lateral movement. Weight shifted onto the left foot, arms balanced outward naturally, head and torso tilted playfully toward the left direction.',
    cameraPrompt: 'Wide frontal view with ample horizontal margin, eye-level 40mm lens',
    lightingPrompt: 'Bright indoor studio lighting, subtle motion trail on left',
    svgOverlay: { type: 'arrowLeft', color: '#8B5CF6', position: 'center-right' },
  },
  moveRight: {
    command: 'moveRight',
    category: 'movement',
    filename: '_moveRight.png',
    environment: 'Colorful child dance studio with clean polished wood floors and warm pastel wall trim',
    scenePrompt: 'The character is stepping sideways toward the right in a cheerful lateral shuffle. Weight shifted onto the right foot, arms balancing naturally, cheerful smile directed toward the right.',
    cameraPrompt: 'Wide frontal view with ample horizontal margin, eye-level 40mm lens',
    lightingPrompt: 'Bright indoor studio lighting, subtle motion trail on right',
    svgOverlay: { type: 'arrowRight', color: '#F97316', position: 'center-right' },
  },
  spin: {
    command: 'spin',
    category: 'movement',
    filename: '_spin.png',
    environment: 'Spacious child playroom with soft round carpet',
    scenePrompt: 'The character is turning and spinning playfully in a 360-degree pirouette twirl. Torso visibly rotating, arms outstretched balancing with wind catching clothing and hair, head tilted with joyful laughter. Subtle elegant circular motion ribbons and tiny sparkling stars curving around character.',
    cameraPrompt: 'Dynamic 45mm lens, centered character with room for outstretched arms',
    lightingPrompt: 'Radiant sparkling illumination, circular swirl shadow on floor',
  },
  slide: {
    command: 'slide',
    category: 'movement',
    filename: '_slide.png',
    environment: 'Beautiful vibrant outdoor children playground on a sunny morning with wood-chip mulch floor',
    scenePrompt: 'The character is happily seated inside a glossy curved rainbow playground slide chute, hands safely resting on the side safety rails, sliding down quickly with wind in hair. Ecstatic laughing expression, dynamic but safe slide posture.',
    cameraPrompt: 'Angled action camera capturing the curve of the slide and child sliding down toward camera',
    lightingPrompt: 'Crisp outdoor sunlight reflecting on glossy slide surface, warm summer atmosphere',
  },
  rideBike: {
    command: 'rideBike',
    category: 'movement',
    filename: '_rideBike.png',
    environment: 'Paved safe park bicycle path bordered by green manicured grass and shade trees',
    scenePrompt: 'The character is properly mounted and riding an age-appropriate children bicycle. Wearing a matching safety bicycle helmet securely buckled. Both hands firmly gripping the handlebars with front bell, feet placed correctly on the pedals, seated naturally on the saddle looking ahead smiling.',
    cameraPrompt: 'Three-quarter side profile action camera, 50mm lens, full bicycle and rider in frame',
    lightingPrompt: 'Warm golden sunlight filtering through trees, soft rotational motion hints on wheel spokes',
  },

  // ==========================================
  // 2. FUN & EMOTIONS (12 Commands)
  // ==========================================
  laugh: {
    command: 'laugh',
    category: 'fun',
    filename: '_laugh.png',
    environment: 'Bright cozy living room corner with colorful plush cushions',
    scenePrompt: 'The character is laughing joyfully from the heart. Natural open-mouth beaming smile, eyes crinkled in expressive genuine happiness, hands clapping or holding tummy in pure glee. Small sparkling golden light accents floating around character.',
    cameraPrompt: 'Close-to-medium 50mm portrait shot, captivating facial expression and sparkling eyes',
    lightingPrompt: 'Warm radiant facial key light, soft volumetric warmth',
  },
  cry: {
    command: 'cry',
    category: 'fun',
    filename: '_cry.png',
    environment: 'Quiet gentle bedroom reading nook with pastel colors and soft drapery',
    scenePrompt: 'The character is visibly sad with a gentle child-friendly weeping expression. Slight pout, clear translucent blue teardrops rolling down cheeks, one hand gently dabbing cheek. Emotional, compassionate, and tender, absolutely no exaggerated horror or trauma.',
    cameraPrompt: 'Eye-level 50mm emotive portrait, respectful framing',
    lightingPrompt: 'Soft diffused melancholic daylight, gentle highlights on tear drops',
  },
  surprised: {
    command: 'surprised',
    category: 'fun',
    filename: '_surprised.png',
    environment: 'Exciting discovery room with science or puzzle books on shelves',
    scenePrompt: 'The character displays genuine delight and wonder. Wide round eyes, raised expressive eyebrows, slightly open mouth in an "O" shape, both hands pressed against cheeks in delightful shock. Small subtle 3D wonder lines in the air.',
    cameraPrompt: 'Centered 50mm eye-level lens, expressive head and upper torso',
    lightingPrompt: 'Bright pop lighting, specular highlights in wide eyes',
  },
  think: {
    command: 'think',
    category: 'fun',
    filename: '_think.png',
    environment: 'Quiet modern study room with wooden desk and globe in soft background',
    scenePrompt: 'The character is thoughtfully touching their chin with index finger, eyes looking slightly upward to the side in deep curiosity and problem solving. A charming semi-translucent 3D thought bubble floats above with a warmly glowing bright yellow idea lightbulb inside.',
    cameraPrompt: 'Medium 50mm shot with sufficient vertical space above head for thought bubble',
    lightingPrompt: 'Soft room ambient light with warm golden illumination radiating from the glowing bulb',
  },
  wave: {
    command: 'wave',
    category: 'fun',
    filename: '_wave.png',
    environment: 'Welcoming front garden gate with blooming colorful flowers and cobblestones',
    scenePrompt: 'The character is waving one hand warmly toward the viewer in a friendly greeting. Open palm clearly visible, fingers naturally spread, charming wide welcoming smile and tilted head.',
    cameraPrompt: 'Eye-level 50mm lens, character greeting directly into camera',
    lightingPrompt: 'Bright welcoming morning sun, friendly sparkling rim light',
  },
  clap: {
    command: 'clap',
    category: 'fun',
    filename: '_clap.png',
    environment: 'Festive school assembly stage with colorful streamers in soft background',
    scenePrompt: 'The character is enthusiastically clapping hands together in applause. Hands positioned cleanly palm-to-palm, ecstatic smile of appreciation and support, small rhythmic 3D soundwave ripple accents between palms.',
    cameraPrompt: 'Frontal 50mm lens, clear visibility of clapping hands',
    lightingPrompt: 'Warm celebratory stage lighting, sparkling star accents',
  },
  dance: {
    command: 'dance',
    category: 'fun',
    filename: '_dance.png',
    environment: 'Festive cultural ballroom or stage with rich carpet and soft ambient stage lamps',
    scenePrompt: 'The character is dancing energetically in authentic traditional Azerbaijani national costume (girls wearing silk kelaghayi headpiece, velvet embroidered vest with gold buta motifs, silver belt, raised graceful arms; boys wearing papakha, chokha with chest gazyrs, silver belt, proud dance stance). Dynamic dance movement, floating 3D music notes and subtle sparkles.',
    cameraPrompt: 'Full body 40mm stage camera, ample headroom for traditional hat/headpiece',
    lightingPrompt: 'Cinematic theater stage spotlight with warm golden ambient fill',
  },
  sing: {
    command: 'sing',
    category: 'fun',
    filename: '_sing.png',
    environment: 'Music studio or karaoke stage with soft purple and blue ambient acoustic panels',
    scenePrompt: 'The character is singing happily and passionately into a modern child-friendly metallic microphone held securely in hand with correct grip. Mouth open in singing melody, head raised joyfully, colorful 3D musical notes floating nearby.',
    cameraPrompt: 'Medium-full 50mm portrait shot, clear microphone and expressive facial performance',
    lightingPrompt: 'Vibrant concert-style rim lighting, glowing musical clef sparkles',
  },
  playInstrument: {
    command: 'playInstrument',
    category: 'fun',
    filename: '_playInstrument.png',
    environment: 'Sunny music room with wooden instruments and sheet music stand in soft background',
    scenePrompt: 'The character is seated or standing comfortably holding and playing a child-sized acoustic guitar. Left hand properly positioned on the guitar neck frets, right hand strumming the strings, body swaying to the rhythm, joyful focused expression.',
    cameraPrompt: 'Three-quarter 45mm angle capturing instrument, hands, and facial expression',
    lightingPrompt: 'Warm timber tones, glossy reflection on guitar body, sparkling music notes',
  },
  playToy: {
    command: 'playToy',
    category: 'fun',
    filename: '_playToy.png',
    environment: 'Warm child bedroom floor with cozy patterned play mat',
    scenePrompt: 'The character is sitting cross-legged on the floor playing joyfully with toys. Interacting naturally with a fluffy brown plush teddy bear and a colorful wooden toy train with carriages on track. Engaged, creative, imaginative smile.',
    cameraPrompt: 'Slightly elevated 45mm camera looking down at seated character and toys',
    lightingPrompt: 'Cozy domestic interior light, soft velvety textures on toys',
  },
  nod: {
    command: 'nod',
    category: 'fun',
    filename: '_nod.png',
    environment: 'Bright classroom with chalkboard and tidy wooden desks in soft background',
    scenePrompt: 'The character is making a clear positive affirmative "yes" head nodding gesture. Happy approving expression, giving an encouraging thumbs-up with one hand, posture leaning slightly forward in agreement.',
    cameraPrompt: 'Straight-on 50mm eye-level portrait',
    lightingPrompt: 'Clear bright educational lighting',
    svgOverlay: { type: 'checkmark', color: '#10B981', position: 'top-right' },
  },
  shakeHead: {
    command: 'shakeHead',
    category: 'fun',
    filename: '_shakeHead.png',
    environment: 'Clean modern dining area or kitchen with fruit bowl in background',
    scenePrompt: 'The character is making a gentle, polite "no" head-shaking gesture. Friendly polite neutral expression, waving one hand gently in a graceful "no thank you" motion, natural anatomy.',
    cameraPrompt: 'Straight-on 50mm eye-level portrait',
    lightingPrompt: 'Soft balanced kitchen daylight',
    svgOverlay: { type: 'cross', color: '#EF4444', position: 'top-right' },
  },

  // ==========================================
  // 3. DAILY ROUTINE (8 Commands)
  // ==========================================
  wakeUp: {
    command: 'wakeUp',
    category: 'daily',
    filename: '_wakeUp.png',
    environment: 'Cozy child bedroom with soft pastel walls, wooden nightstand, and window with white sheer curtains',
    scenePrompt: 'The character is inside a cozy bedroom, sitting upright in a comfortable child bed immediately after waking. Quilt draped comfortably across legs, soft pillow behind back. Morning golden sunlight streaming warmly through the window. A charming smiling alarm clock on the bedside table. Character stretching both arms upward into the air, slightly sleepy but happy morning face. Unmistakably conveys "I just woke up".',
    cameraPrompt: 'Three-quarter 45mm perspective showing bed, bedside table with alarm clock, window light',
    lightingPrompt: 'Dramatic warm morning sunrise shafts streaming through window glass, atmospheric dust motes',
  },
  sleep: {
    command: 'sleep',
    category: 'daily',
    filename: '_sleep.png',
    environment: 'Peaceful night-time child bedroom with star-patterned wallpaper and moonlit window',
    scenePrompt: 'The character is sleeping peacefully inside a cozy child bed. Head naturally resting on a fluffy soft blue pillow, eyes closed serenely in sweet dreams. Soft quilted blanket tucked neatly up to chest. Outside the window, a gentle crescent moon and twinkling stars shine. Subtle dreamy 3D "Zzz" symbols floating peacefully.',
    cameraPrompt: 'Calm three-quarter 50mm camera angled toward the sleeping child in bed',
    lightingPrompt: 'Soft blue nocturnal moonlight balanced with warm amber nightlight glow',
  },
  eat: {
    command: 'eat',
    category: 'daily',
    filename: '_eat.png',
    environment: 'Bright cheerful family dining kitchen with wooden dining table and window',
    scenePrompt: 'The character is sitting at a clean dining table eating healthy delicious food. Holding a crisp fresh red apple in one hand and a spoon over a colorful ceramic bowl with nutritious cereal or fruit soup. Healthy, appetizing, happy eating environment.',
    cameraPrompt: 'Table-level 50mm medium shot showing table surface, food bowl, and character',
    lightingPrompt: 'Fresh morning kitchen daylight, crisp reflections on ceramic bowl and apple skin',
  },
  drink: {
    command: 'drink',
    category: 'daily',
    filename: '_drink.png',
    environment: 'Clean modern kitchen counter with fruit basket in soft background',
    scenePrompt: 'The character is drinking fresh clean water from a clear child-safe glass tumbler held steadily with both hands. Sipping through a colorful bendy straw, with a fresh lemon slice decorating the glass rim. Refreshing, hydrated, joyful expression.',
    cameraPrompt: 'Eye-level 50mm shot focused on glass, hands, and satisfied expression',
    lightingPrompt: 'Sparkling clean sunlight refracting through clear water and ice cubes',
  },
  bathe: {
    command: 'bathe',
    category: 'daily',
    filename: '_bathe.png',
    environment: 'Bright, sparkling clean child-safe bathroom with glossy light-blue ceramic wall tiles',
    scenePrompt: 'Child-safe bathroom scene. The character is in side profile under a modern chrome shower head spraying gentle clean cascading water streams over head and shoulders. The character wears appropriate modesty child swimwear/bathrobe or is artistically draped in thick fluffy soap foam. Iridescent shimmering soap bubbles floating in air and a cheerful yellow rubber duck nearby.',
    cameraPrompt: 'Profile to three-quarter 45mm shot, clean bathroom framing, strict child-appropriate coverage',
    lightingPrompt: 'Sparkling bathroom tile illumination, glistening water droplet caustics',
  },
  wash: {
    command: 'wash',
    category: 'daily',
    filename: '_wash.png',
    environment: 'Modern child bathroom with white porcelain sink vanity and round mirror',
    scenePrompt: 'The character is standing at a child-height sink washbasin actively washing hands. Hands correctly positioned under running water from a polished faucet, rubbing rich foaming white soap lather between palms and fingers. Cheerful proud hygiene smile.',
    cameraPrompt: 'Medium 45mm shot capturing character torso, sink, faucet, and foaming hands',
    lightingPrompt: 'Crisp clean bathroom lighting, iridescent bubbles and splashing water droplets',
  },
  comb: {
    command: 'comb',
    category: 'daily',
    filename: '_comb.png',
    environment: 'Neat bedroom dressing corner with vanity mirror and soft floral wallpaper',
    scenePrompt: 'The character is gently combing or brushing their hair using a colorful child-friendly hairbrush held with natural arm position. Looking into a mirror with a proud, neat smile, hair looking smooth, glossy, and tidy with delicate shine glints.',
    cameraPrompt: 'Frontal three-quarter 50mm portrait shot showing brush in hand and neat hair',
    lightingPrompt: 'Flattering vanity lighting with crisp specular highlights along hair strands',
  },
  dress: {
    command: 'dress',
    category: 'daily',
    filename: '_dress.png',
    environment: 'Organized child bedroom beside an open wooden wardrobe with neat colorful hangers',
    scenePrompt: 'The character is getting dressed in the bedroom. Holding up a colorful freshly-pressed clean t-shirt on a wooden hanger against themselves, smiling enthusiastically as they choose their outfit. Tidy bedroom environment, clothes neatly arranged.',
    cameraPrompt: 'Full body 45mm lens, wardrobe and outfit options visible in scene',
    lightingPrompt: 'Warm morning light filling bedroom, crisp fabric textures',
  },

  // ==========================================
  // 4. LEARNING & CREATIVITY (10 Commands)
  // ==========================================
  read: {
    command: 'read',
    category: 'learning',
    filename: '_read.png',
    environment: 'Cozy library or classroom reading corner with bookshelf and soft beanbag',
    scenePrompt: 'The character is holding open a large, colorful illustrated children storybook with both hands. Book correctly oriented toward the character, eyes focused on vivid illustrations and text with fascination and curiosity. Cozy educational environment.',
    cameraPrompt: 'Slightly angled 50mm shot showcasing book pages and focused child gaze',
    lightingPrompt: 'Warm golden reading lamp illumination, magical story dust sparks rising',
  },
  write: {
    command: 'write',
    category: 'learning',
    filename: '_write.png',
    environment: 'Sunlit school classroom or home study area with clean wooden study desk',
    scenePrompt: 'The character is sitting at a wooden study desk writing diligently into an open lined school notebook using a sharpened yellow pencil. Correct ergonomic pencil grip, upright posture, focused proud smile.',
    cameraPrompt: 'Over-the-table 45mm perspective showing desk, notebook lines, and writing hand',
    lightingPrompt: 'Bright focused study lamp light balanced with natural window fill',
  },
  draw: {
    command: 'draw',
    category: 'learning',
    filename: '_draw.png',
    environment: 'Creative art room with wooden easel, art racks, and colorful supply jars',
    scenePrompt: 'The character is standing before an artist wooden easel, drawing a vibrant rainbow and smiling yellow sun onto a large drawing paper board using a crayon. Expressive proud young artist expression.',
    cameraPrompt: 'Three-quarter 45mm shot showing character, easel canvas, and drawing hand',
    lightingPrompt: 'Bright north-facing art studio light, rich vivid pigment textures',
  },
  paint: {
    command: 'paint',
    category: 'learning',
    filename: '_paint.png',
    environment: 'Art studio workspace with drying racks and paint-splattered work table',
    scenePrompt: 'The character is wearing a protective child art smock/apron. Holding a classic wooden artist palette with dollops of primary paint colors in one hand, and holding a paintbrush dripping vibrant blue paint in the other, smiling creatively at their canvas.',
    cameraPrompt: 'Frontal three-quarter 45mm shot, palette and brush clearly visible',
    lightingPrompt: 'Rich colorful studio lighting, wet glossy paint textures',
  },
  cut: {
    command: 'cut',
    category: 'learning',
    filename: '_cut.png',
    environment: 'Craft table with colorful sheets of origami paper and rulers',
    scenePrompt: 'The character is safely cutting colored construction paper using round-tipped child safety scissors. Correct safe scissor grip with both hands coordinating, cutting out neat star and heart shapes. Craft table environment.',
    cameraPrompt: 'Medium 45mm shot focused on crafting hands and paper cutouts',
    lightingPrompt: 'Crisp bright work light, colorful paper confetti and star cutouts on table',
  },
  count: {
    command: 'count',
    category: 'learning',
    filename: '_count.png',
    environment: 'Montessori early learning classroom with low wooden shelves and educational toys',
    scenePrompt: 'The character is learning to count using large colorful wooden building cubes. Counting on fingers with an enthusiastic mathematical smile, interacting with blocks.',
    cameraPrompt: 'Child-level 45mm shot showing character and counting materials',
    lightingPrompt: 'Warm natural classroom sunlight, clean shadows',
    svgOverlay: { type: 'countBlocks', color: '#06B6D4', position: 'top-right' },
  },
  talk: {
    command: 'talk',
    category: 'learning',
    filename: '_talk.png',
    environment: 'Playful preschool group activity circle with colorful rug',
    scenePrompt: 'The character is actively speaking and sharing a story. Animated natural hand gestures, mouth open mid-word, engaging warm facial expression. Subtle clean speech soundwave visual cues in the air.',
    cameraPrompt: 'Frontal eye-level 50mm portrait shot, communicative posture',
    lightingPrompt: 'Inviting, friendly ambient room illumination',
  },
  build: {
    command: 'build',
    category: 'learning',
    filename: '_build.png',
    environment: 'Spacious playroom floor with large storage bins of building materials',
    scenePrompt: 'The character is sitting on the floor carefully placing the final block on top of a tall, colorful tower made of interlocking plastic Lego and wooden construction blocks. Hands interacting naturally with blocks, proud structural achievement expression.',
    cameraPrompt: 'Three-quarter 45mm shot showing seated child and tall impressive tower',
    lightingPrompt: 'Vibrant indoor lighting, glossy reflections on plastic toy bricks',
  },
  point: {
    command: 'point',
    category: 'learning',
    filename: '_point.png',
    environment: 'Classroom science corner or outdoor nature garden with interesting birds/butterflies',
    scenePrompt: 'The character is clearly pointing toward an exciting discovery in the distance. Arm extended straight, index finger clearly and accurately formed pointing toward target, eyes directed intently at target, eager curious expression.',
    cameraPrompt: 'Side three-quarter 45mm perspective following the pointing arm line of action',
    lightingPrompt: 'Clear directional light highlighting the pointing finger',
    svgOverlay: { type: 'target', color: '#F43F5E', position: 'top-right' },
  },
  stretch: {
    command: 'stretch',
    category: 'learning',
    filename: '_stretch.png',
    environment: 'Bright morning sports studio or gymnastics mat with green gym flooring',
    scenePrompt: 'The character is performing a healthy full-body gymnastic stretch. Standing on tiptoes, extending both arms straight up toward the ceiling with fingers open, elongating spine, taking a deep breath with refreshing smile.',
    cameraPrompt: 'Full body 40mm vertical shot with ample clearance above raised arms',
    lightingPrompt: 'Energizing bright morning light, athletic rim highlights',
  },

  // ==========================================
  // 5. SOCIAL & ACTIVITIES (15 Commands)
  // ==========================================
  hug: {
    command: 'hug',
    category: 'social',
    filename: '_hug.png',
    environment: 'Comfortable bedroom with soft rug and warm atmosphere',
    scenePrompt: 'The character is warmly hugging a giant, fluffy brown plush teddy bear with both arms wrapped around it tightly. Eyes closed affectionately with cheek resting against the teddy bear fur, gentle peaceful smile. Subtle small 3D heart sparkles floating nearby.',
    cameraPrompt: 'Medium 50mm portrait shot, emphasis on tender embrace',
    lightingPrompt: 'Warm cozy golden domestic lighting, soft fur texture illumination',
  },
  holdHands: {
    command: 'holdHands',
    category: 'social',
    filename: '_holdHands.png',
    environment: 'Sunny community park meadow with dandelion flowers and blue sky',
    scenePrompt: 'The character is holding hands with another friendly child of similar age. Natural hand positioning with clasped fingers, standing side by side, beaming smiles of friendship and unity. Inclusive neutral presentation, rainbow of friendship in background.',
    cameraPrompt: 'Wide two-figure 40mm camera, characters centered and balanced',
    lightingPrompt: 'Brilliant outdoor daylight, joyful warmth',
  },
  help: {
    command: 'help',
    category: 'social',
    filename: '_help.png',
    environment: 'Playground pathway with wood chips and green lawn',
    scenePrompt: 'The character is compassionately helping another child pick up dropped toys or stand up safely. Extending a supportive, caring hand downward, gentle reassuring smile of kindness and empathy. Clear communication of helping and friendship.',
    cameraPrompt: 'Action 45mm shot, emphasis on the reaching supportive hand and caring face',
    lightingPrompt: 'Warm empathetic golden sunlight',
  },
  openDoor: {
    command: 'openDoor',
    category: 'social',
    filename: '_openDoor.png',
    environment: 'Charming country cottage room with rustic wooden floor',
    scenePrompt: 'The character is standing beside a paneled wooden door, hand placed correctly on the brass door handle and swinging the door open toward a sun-drenched green flower garden outside. Bright natural sunlight and gentle breeze streaming in through the doorway.',
    cameraPrompt: 'Three-quarter 40mm perspective showing doorway, handle, character, and outdoor view',
    lightingPrompt: 'Dramatic golden sunbeam volume light piercing through the open doorway',
  },
  closeDoor: {
    command: 'closeDoor',
    category: 'social',
    filename: '_closeDoor.png',
    environment: 'Warm child bedroom with wooden doorframe and carpeted floor',
    scenePrompt: 'The character is standing facing a sturdy wooden bedroom door, placing hand on the brass doorknob and pushing the door gently shut until it latches securely. Natural, purposeful posture, focused neat expression.',
    cameraPrompt: 'Interior 45mm shot showing door panel, brass handle, and character closing it',
    lightingPrompt: 'Interior room warmth, crisp shadows along door edges',
  },
  putAway: {
    command: 'putAway',
    category: 'social',
    filename: '_putAway.png',
    environment: 'Tidy, organized playroom with labeled toy cubbies and bins',
    scenePrompt: 'The character is kneeling beside a colorful plastic toy storage box, holding a toy with both hands and carefully placing it inside to tidy the room. Sense of responsibility and pride in a clean room.',
    cameraPrompt: 'Low 45mm perspective capturing storage box and character placing toy',
    lightingPrompt: 'Bright clean playroom light, neat organization sparkle glints',
  },
  collect: {
    command: 'collect',
    category: 'social',
    filename: '_collect.png',
    environment: 'Spacious playroom with scattered play balls and blocks on floor',
    scenePrompt: 'The character is bending down to collect scattered colorful play balls and blocks from the floor, placing them into a woven wicker basket held on arm. Clear gathering and collecting action, cheerful active expression.',
    cameraPrompt: 'Medium 40mm angle showing scattered items and collection basket',
    lightingPrompt: 'Lively daylight, realistic shadow contacts for each collected toy',
  },
  clean: {
    command: 'clean',
    category: 'social',
    filename: '_clean.png',
    environment: 'Clean kitchen or playroom with shiny hardwood flooring',
    scenePrompt: 'The character is happily sweeping the floor using an age-appropriate colorful child broom and dustpan. Natural sweeping posture, proud and energetic expression, tiny dazzling white cleanliness sparkles radiating from the swept floor.',
    cameraPrompt: 'Full body 45mm shot, broom handle and floor clearly framed',
    lightingPrompt: 'Bright sparkling clean illumination with floor surface reflections',
  },
  bring: {
    command: 'bring',
    category: 'social',
    filename: '_bring.png',
    environment: 'Festive party room with colorful bunting and warm party lamps',
    scenePrompt: 'The character is walking forward toward the viewer carrying a beautifully wrapped gift box with a giant satin golden ribbon bow securely held with both hands. Presenting the gift with a beaming joyful smile of generosity.',
    cameraPrompt: 'Frontal three-quarter 50mm shot moving toward camera',
    lightingPrompt: 'Festive warm celebratory lighting, glistening satin ribbon textures',
  },
  takeAway: {
    command: 'takeAway',
    category: 'social',
    filename: '_takeAway.png',
    environment: 'Sunny hallway or garden path leading into background',
    scenePrompt: 'The character is walking away into the scene while securely carrying a small cardboard parcel box with both hands. Body direction and footsteps clearly communicate carrying the object away to deliver it.',
    cameraPrompt: 'Three-quarter reverse perspective 45mm shot following the movement',
    lightingPrompt: 'Directional sunlight showing path and motion progression',
  },
  carry: {
    command: 'carry',
    category: 'social',
    filename: '_carry.png',
    environment: 'School entrance walkway on a crisp sunny morning',
    scenePrompt: 'The character is standing proudly ready for school, wearing a colorful, ergonomic structured children school backpack on back with straps properly adjusted over shoulders. Upright posture, enthusiastic ready-for-learning expression.',
    cameraPrompt: 'Three-quarter profile 50mm shot showcasing backpack straps and posture',
    lightingPrompt: 'Crisp morning school sunshine, fabric weave reflections on backpack',
  },
  pull: {
    command: 'pull',
    category: 'social',
    filename: '_pull.png',
    environment: 'Park walkway or paved garden path with grass border',
    scenePrompt: 'The character is gripping a pull-cord handle and leaning forward in dynamic motion, pulling a classic red wooden four-wheeled wagon loaded with plush toys behind them. Correct physical biomechanics and tension between character and wagon.',
    cameraPrompt: 'Action 40mm shot capturing character in front, rope handle, and wagon behind',
    lightingPrompt: 'Sunny park daylight with rolling wheel motion accents',
  },
  scatter: {
    command: 'scatter',
    category: 'social',
    filename: '_scatter.png',
    environment: 'Joyous celebration hall or birthday party room',
    scenePrompt: 'The character is tossing hands high into the air in pure celebratory glee as a spectacular burst of colorful party confetti pieces and shiny curled streamer ribbons explode and flutter downward everywhere. Exuberant laughing expression.',
    cameraPrompt: 'Dynamic 40mm wide shot capturing air filled with falling confetti',
    lightingPrompt: 'Prismatic party lighting, glistening reflections on metallic confetti foil',
  },
  waterPlant: {
    command: 'waterPlant',
    category: 'social',
    filename: '_waterPlant.png',
    environment: 'Bright sunny garden terrace or indoor sunroom with terracotta flowerpots and green ferns',
    scenePrompt: 'The character is holding a small colorful child watering can tilted forward, pouring a crystal clear gentle shower stream of water directly onto a thriving green potted plant with blossoming flower. Nurturing, caring expression, glistening water droplets on green leaves.',
    cameraPrompt: 'Three-quarter 45mm shot focusing on watering can spout and blooming plant',
    lightingPrompt: 'Lush natural sunlight, sparkling translucent water stream and leaf highlights',
  },
  lightMatch: {
    command: 'lightMatch',
    category: 'social',
    filename: '_lightMatch.png',
    environment: 'Cozy evening living room with hearth mantlepiece in soft background',
    scenePrompt: 'Safe educational representation. The character is standing safely near a beautiful vintage brass and glass candle lantern sitting securely on a wooden table. The character is watching the warm, flickering golden flame inside with gentle, fascinated eyes. Warm golden candlelight radiates across face and surroundings. Strictly avoids child playing with fire.',
    cameraPrompt: 'Atmospheric 50mm medium portrait shot focusing on lantern and character face',
    lightingPrompt: 'Dramatic, intimate warm candlelight illumination painting the character with amber glow',
  },
};
