import type { CommandDefinition } from '../types';

export const COMMANDS: CommandDefinition[] = [
  // Əsas hərəkətlər
  { command: 'sit',          icon: '🪑', color: '#7c3aed', gradient: 'bg-btn-purple' },
  { command: 'stand',        icon: '🧍', color: '#3b82f6', gradient: 'bg-btn-blue'   },
  { command: 'run',          icon: '🏃', color: '#f97316', gradient: 'bg-btn-orange' },
  { command: 'walkForward',  icon: '⬆️', color: '#10b981', gradient: 'bg-btn-green'  },
  { command: 'walkBackward', icon: '⬇️', color: '#f43f5e', gradient: 'bg-btn-coral'  },
  { command: 'moveLeft',     icon: '⬅️', color: '#8b5cf6', gradient: 'bg-btn-purple' },
  { command: 'moveRight',    icon: '➡️', color: '#f97316', gradient: 'bg-btn-orange' },
  { command: 'jump',         icon: '🦘', color: '#f59e0b', gradient: 'bg-btn-yellow' },
  { command: 'wave',         icon: '👋', color: '#06b6d4', gradient: 'bg-btn-cyan'   },
  { command: 'spin',         icon: '🔄', color: '#3b82f6', gradient: 'bg-btn-blue'   },
  { command: 'stop',         icon: '🛑', color: '#f43f5e', gradient: 'bg-btn-coral'  },
  { command: 'clap',         icon: '👏', color: '#f59e0b', gradient: 'bg-btn-yellow' },
  { command: 'dance',        icon: '💃', color: '#ec4899', gradient: 'bg-btn-pink'   },
  // İfadələr
  { command: 'nod',          icon: '👍', color: '#10b981', gradient: 'bg-btn-green'  },
  { command: 'shakeHead',    icon: '🙅', color: '#ec4899', gradient: 'bg-btn-pink'   },
  { command: 'laugh',        icon: '😂', color: '#f59e0b', gradient: 'bg-btn-yellow' },
  { command: 'cry',          icon: '😢', color: '#3b82f6', gradient: 'bg-btn-blue'   },
  { command: 'think',        icon: '🤔', color: '#8b5cf6', gradient: 'bg-btn-purple' },
  // Fəaliyyətlər
  { command: 'read',         icon: '📖', color: '#10b981', gradient: 'bg-btn-green'  },
  { command: 'write',        icon: '✏️', color: '#f97316', gradient: 'bg-btn-orange' },
  { command: 'draw',         icon: '🎨', color: '#ec4899', gradient: 'bg-btn-pink'   },
  { command: 'sing',         icon: '🎤', color: '#7c3aed', gradient: 'bg-btn-purple' },
  { command: 'count',        icon: '🔢', color: '#06b6d4', gradient: 'bg-btn-cyan'   },
  { command: 'point',        icon: '👆', color: '#f43f5e', gradient: 'bg-btn-coral'  },
  // Gündəlik
  { command: 'eat',          icon: '🍎', color: '#f43f5e', gradient: 'bg-btn-coral'  },
  { command: 'drink',        icon: '🥤', color: '#06b6d4', gradient: 'bg-btn-cyan'   },
  { command: 'sleep',        icon: '😴', color: '#8b5cf6', gradient: 'bg-btn-purple' },
  { command: 'stretch',      icon: '🙆', color: '#10b981', gradient: 'bg-btn-green'  },
];

export const COMMAND_AZ_LABELS: Record<string, { label: string; icon: string }> = {
  'sit': { label: 'Otur', icon: '🪑' },
  'stand': { label: 'Dur (Qalx)', icon: '🧍' },
  'run': { label: 'Qaç', icon: '🏃' },
  'jump': { label: 'Tullan / Oppan', icon: '🦘' },
  'stop': { label: 'Dayan', icon: '🛑' },
  'walk': { label: 'Yol ilə get', icon: '🚶' },
  'walkForward': { label: 'Önə', icon: '⬆️' },
  'walkBackward': { label: 'Geriyə', icon: '⬇️' },
  'moveLeft': { label: 'Sola', icon: '⬅️' },
  'moveRight': { label: 'Sağa', icon: '➡️' },
  'spin': { label: 'Dön', icon: '🔄' },
  'slide': { label: 'Sürüş', icon: '🛝' },
  'rideBike': { label: 'Sür (Velosiped)', icon: '🚲' },
  'laugh': { label: 'Gül', icon: '😂' },
  'cry': { label: 'Ağla', icon: '😢' },
  'surprised': { label: 'Təəccüblən', icon: '😲' },
  'think': { label: 'Düşün / Fikirləş', icon: '🤔' },
  'wave': { label: 'Əl salla', icon: '🖐️' },
  'clap': { label: 'Əl çal', icon: '👏' },
  'dance': { label: 'Oyna (Musiqi)', icon: '💃' },
  'sing': { label: 'Oxu (Musiqi)', icon: '🎤' },
  'playInstrument': { label: 'Çal (Musiqi)', icon: '🎸' },
  'playToy': { label: 'Oyna (Oyuncaq)', icon: '🧸' },
  'nod': { label: 'Bəli (baş)', icon: '👍' },
  'shakeHead': { label: 'Xeyr (baş)', icon: '🙅' },
  'wakeUp': { label: 'Dur (Oyan)', icon: '⏰' },
  'sleep': { label: 'Yat (Yuxu)', icon: '😴' },
  'eat': { label: 'Yemək ye', icon: '🍎' },
  'drink': { label: 'Su iç', icon: '🥤' },
  'bathe': { label: 'Çim (Duş al)', icon: '🚿' },
  'wash': { label: 'Əlini yu', icon: '🧼' },
  'comb': { label: 'Dara (Saçını)', icon: '🪮' },
  'dress': { label: 'Geyin', icon: '👕' },
  'read': { label: 'Oxu (Kitab)', icon: '📖' },
  'write': { label: 'Yaz', icon: '✏️' },
  'draw': { label: 'Çək (Rəsm)', icon: '🎨' },
  'paint': { label: 'Rənglə', icon: '🖌️' },
  'cut': { label: 'Kəs (Qayçı)', icon: '✂️' },
  'count': { label: 'Say', icon: '🔢' },
  'talk': { label: 'Danış', icon: '💬' },
  'build': { label: 'Düzəlt', icon: '🧱' },
  'point': { label: 'Göstər', icon: '👆' },
  'stretch': { label: 'Gəril', icon: '🙆' },
  'hug': { label: 'Qucaqla', icon: '🤗' },
  'holdHands': { label: 'Əl-ələ tut', icon: '🤝' },
  'help': { label: 'Kömək et', icon: '❤️' },
  'openDoor': { label: 'Aç (Qapı)', icon: '🚪' },
  'closeDoor': { label: 'Bağla (Qapı)', icon: '🔒' },
  'putAway': { label: 'Yerinə qoy', icon: '📦' },
  'collect': { label: 'Topla (Əşya)', icon: '🧺' },
  'clean': { label: 'Təmizlə', icon: '🧹' },
  'bring': { label: 'Gətir', icon: '🎁' },
  'takeAway': { label: 'Apar', icon: '🚶‍♂️' },
  'carry': { label: 'Daşı', icon: '🎒' },
  'pull': { label: 'Dart', icon: '🪢' },
  'scatter': { label: 'Dağıt', icon: '💥' },
  'waterPlant': { label: 'Sula (Bitki)', icon: '🪴' },
  'lightMatch': { label: 'Yandır (Kibrit)', icon: '🕯️' },
};
